name: Makefile CI Python 3.8

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: make install

    - name: Test
      run: make test

    - name: Lint
      run: make lint

    - name: Format
      run: make format
